sonar.projectKey=LBHackney-IT_lbh-housing-api
sonar.organization=lbhackney-it
sonar.sources=HousingRegisterApi
sonar.tests=HousingRegisterApi.Tests
sonar.test.inclusions=HousingRegisterApi.Tests/**
sonar.exclusions=HousingRegisterApi.Tests/**
sonar.dotnet.excludeTestProjects=true
sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"