service: housing-register-api
provider:
  name: aws
  runtime: dotnetcore3.1
  memorySize: 2048
  tracing:
    lambda: true
    apiGateway: true
  vpc: ${self:custom.vpc.${opt:stage}}
  stage: ${opt:stage}
  region: eu-west-2
  environment:
    HOUSINGREGISTER_EXPORT_BUCKET_NAME: housingregister-exports-${self:provider.stage}-bucket
  apiGateway:
    apiKeys:
      - api-key-${self:service}-${self:provider.stage}
    usagePlan:
      throttle:
        burstLimit: 200
        rateLimit: 100
package:
  artifact: ./bin/release/netcoreapp3.1/housing-register-api.zip

functions:
  HousingRegisterApi:
    name: ${self:service}-${self:provider.stage}
    handler: HousingRegisterApi::HousingRegisterApi.LambdaEntryPoint::FunctionHandlerAsync
    role: lambdaExecutionRole
    timeout: 30
    environment:
      HACKNEY_JWT_SECRET: ${ssm:/housing-register/${self:provider.stage}/hackney-jwt-secret}
      NOTIFY_API_KEY: ${ssm:/housing-register/${self:provider.stage}/notify-api-key}
      NOTIFY_TEMPLATE_VERIFY_CODE: ${ssm:/housing-register/${self:provider.stage}/notify-template-verify-code}
      HOUSINGREGISTER_SNS_ARN: ${ssm:/sns-topic/${self:provider.stage}/housingregister/arn}
      NOVALET_SNS_ARN: ${ssm:/sns-topic/${self:provider.stage}/novaletexport-sns-topic/arn}
      EVIDENCE_API_URL: ${ssm:/housing-register/${self:provider.stage}/evidence-api/base-url}
      EVIDENCE_API_REQUESTED_BY: ${ssm:/housing-register/${self:provider.stage}/evidence-api/requested-by}
      EVIDENCE_API_GET_EVIDENCE_REQUESTS_TOKEN: ${ssm:/housing-register/${self:provider.stage}/evidence-api/get/evidence-requests/token}
      EVIDENCE_API_POST_EVIDENCE_REQUESTS_TOKEN: ${ssm:/housing-register/${self:provider.stage}/evidence-api/post/evidence-requests/token}
      ACTIVITYHISTORY_API_URL: ${ssm:/housing-register/${self:provider.stage}/activityhistory-api/base-url}
    events:
      - http:
          path: /{proxy+}
          method: ANY
          private: true
  HousingRegisterBedroomRecalulator:
    name: ${self:service}-${self:provider.stage}-bedroom-recalculator
    handler: HousingRegisterApi::HousingRegisterApi.V1.Functions.RedroomRecalculatorFunction::Handle
    role: lambdaExecutionRole
    timeout: 300
    events:
      - schedule: rate(1 day)
  HousingRegisterNovaletExportGenerator:
    dispatcher:
      handler: HousingRegisterApi::HousingRegisterApi.V1.Functions.NovaletExportGeneratorFunction::Handle.novaletexport-sns-topic
      role: lambdaExecutionRole
      timeout: 300
      events:
      - sns: arn:aws:sns:eu-west-2:364864573329:novaletexport-sns-topic
  HousingRegisterNovaletExportUpload:
    name: ${self:service}-${self:provider.stage}-novalet-export-upload
    handler: HousingRegisterApi::HousingRegisterApi.V1.Functions.FtpUploadNovaletExportFunction::Handle
    role: lambdaExecutionRole
    events:
      - schedule: cron(30 16 ? * MON-FRI *)
resources:
  Resources:
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: ${self:service}-${self:provider.stage}-sg
        GroupDescription: Allow all outbound traffic
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
        VpcId: ${self:custom.vpcId.${opt:stage}}
    lambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /${self:service}/${self:provider.stage}/
        RoleName: ${self:service}-lambdaExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        Policies:
          - PolicyName: dynamoDBAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "dynamodb:BatchGet*"
                    - "dynamodb:BatchWrite"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:DescribeStream"
                    - "dynamodb:DescribeTable"
                    - "dynamodb:Get*"
                    - "dynamodb:PutItem"
                    - "dynamodb:Query"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:dynamodb"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "table/HousingRegister"
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:dynamodb"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "table/HousingRegister/index/*"
          - PolicyName: manageLogs
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "ServerlessDeploymentBucket"
          - PolicyName: lambdaInvocation
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: "*"
          - PolicyName: postToSns
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "sns:Publish"
                  Resource:
                    - ${ssm:/sns-topic/${self:provider.stage}/housingregister/arn}
          - PolicyName: bucketAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:ListBucket"
                    - "s3:GetObject"
                    - "s3:GetObjectTagging"
                    - "s3:PutObject"
                    - "s3:PutObjectTagging"
                    - "s3:DeleteObject"
                  Resource:
                    - "arn:aws:s3:::${self:provider.environment.HOUSINGREGISTER_EXPORT_BUCKET_NAME}"
                    - "arn:aws:s3:::${self:provider.environment.HOUSINGREGISTER_EXPORT_BUCKET_NAME}/*"
custom:
  vpcId:
    development: vpc-0d15f152935c8716f
    staging: vpc-064521a7a4109ba31
    production: vpc-0ce853ddb64e8fb3c
  vpc:
    development:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        - subnet-0140d06fb84fdb547
        - subnet-05ce390ba88c42bfd
    staging:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        - subnet-0743d86e9b362fa38
        - subnet-0ea0020a44b98a2ca
    production:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        - subnet-06a697d86a9b6ed01
        - subnet-0beb266003a56ca82
